# Generated by Django 4.2.23 on 2025-08-16 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deliverylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylocation',
            name='delivery_agent',
            field=models.OneToOneField(limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='emirates_id',
            field=models.FileField(blank=True, null=True, upload_to='documents/emirates_ids/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='documents/passports/'),
        ),
    ]
