# Generated by Django 4.2.23 on 2025-08-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_deliverylocation_delivery_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
