# Generated by Django 4.2.23 on 2025-08-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(max_length=5),
        ),
    ]
