# Generated by Django 4.2.23 on 2025-08-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='digitalsignature',
            name='signature_data',
            field=models.FileField(blank=True, null=True, upload_to='documents/signatures/'),
        ),
    ]
