# Generated by Django 4.2.23 on 2025-08-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_passport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
