# Generated by Django 4.2.23 on 2025-08-21 11:32

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transaction_address_transaction_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('emirates_id_front', models.FileField(blank=True, null=True, upload_to='guests/emirates_id_front/')),
                ('emirates_id_back', models.FileField(blank=True, null=True, upload_to='guests/emirates_id_back/')),
                ('passport', models.FileField(blank=True, null=True, upload_to='guests/passports/')),
                ('face_scan', models.ImageField(blank=True, null=True, upload_to='guests/face_scans/')),
                ('temp_token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
