# Generated by Django 4.2.23 on 2025-08-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff'), ('delivery', 'Delivery'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
