# Generated by Django 4.2.23 on 2025-08-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='الرصيد الكلي للمستخدم في النظام (محفظة رقمية)', max_digits=12),
        ),
    ]
