# Generated by Django 4.2.23 on 2025-08-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_type',
            field=models.CharField(choices=[('instant', 'Instant Delivery'), ('scheduled', 'Scheduled Delivery')], default='instant', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='scheduled_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
