# Generated by Django 4.2.23 on 2025-08-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_transaction_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
